spaces = ' ' * 25
print('%s 12 Butts Wynd' % spaces)
print('%s Twinklebottom Heath' % spaces)
print('%s West Snoring' % spaces)
print()
print()
print('dear sir')
print()
print('I wish to report that titles are missing from the')
print('outside toilet foof.')
print('i think it was bad wind the other night that blew then away.')
print()
print('Regards')
print('Malcolm Dithering')
